### ISSUE TITLE
GetBlockTransfersByHeight return error

### ISSUE THREAD

**Issue by lucky777strike** [make-software/casper-go-sdk#45]
Hello, i'am trying to make call client.GetBlockTransfersByHeight(c.ctx, uint64(i)) in testnet. it's return error

"failed to unmarshal rpc result, details: can't parse string to key, source: "

block height: 2005854
rpcnode: 65.21.238.180, 46.4.20.60

**Comment by koltsov-iv** [comment]
I can't reproduce. Please make sure that you use latest version of casper-go-sdk.

**Comment by lucky777strike** [comment]
code snipped to reproduce this issue

```go
package main

import (
	"context"
	"log"
	"net/http"

	"github.com/make-software/casper-go-sdk/casper"
)

func main() {
	rpc_url := "http://65.21.238.180:7777/rpc"
	client := casper.NewRPCClient(casper.NewRPCHandler(rpc_url, http.DefaultClient))
	_, err := client.GetBlockTransfersByHeight(context.Background(), 2005854)
	if err != nil {
		log.Println(err)
	}
}
```

in result we have error: "failed to unmarshal rpc result, details: can't parse string to key, source:"
This is repeated on any testnet node with this block
