### ISSUE TITLE
Potential bug with Casper node 1.5: Failure to deserialize the System proposed switch block

### ISSUE THREAD

**Issue by mrkara** [make-software/casper-go-sdk#46]
Try to deserialize the "System proposed switch block" -> the .Net SDK fails because the Proposer is normally a PublicKey but now it is "00" which is invalid.

The system-propsoed switch block: https://cspr.live/block/1562c81ea1623b6c882370b4a659b797e06e30ddbc0053b6b0d3a1aef71c6d33

First discovered on the .NET SDK: https://github.com/make-software/casper-net-sdk/issues/37

**Comment by koltsov-iv** [comment]
we've fixed it in v1.2
